### ISSUE TITLE
Empty Velocity

### ISSUE THREAD

**Issue by borongyuan** [erlerobot/cartpole_gazebo#1]
Hi, is this package still under development? It seems the topic /cart_pole/joint_states doesn't contain any velocity info, since you are using libgazebo_ros_joint_state_publisher.so.

**Comment by ahcorde** [comment]
I made a [PR](https://github.com/ros-simulation/gazebo_ros_pkgs/commit/69622d297a2eb9b7db13fd2a76b419a21d0cef03) some days ago to include velocity in  libgazebo_ros_joint_state_publisher.so

For now, you can compile this package using catkin until new packages will be release

**Comment by borongyuan** [comment]
Thanks

**Comment by rdockterjr** [comment]
I didn't find this issues solution particularly complete. 
Am I correct in assuming that depending on the ROS version I am using I need to clone the gazebo plugins repo: https://github.com/ros-simulation/gazebo_ros_pkgs/tree/kinetic-devel/gazebo_plugins

And then change the gazebo_ros_joint_state_publisher.cpp file such that the publishJointStates() function also incorporates velocity in it's  joint_state_ message?

**Comment by borongyuan** [comment]
Hi, @rdockterjr ,
you need to clone that repo, but you don't need to modify the code. @ahcorde has added the API call, and it's already merged to the kinetic-devel branch. Just compile it.
The change is contained in the 2.5.15 release, I don't know why the ros-kinetic-gazebo8-ros-pkgs is still staying in 2.5.14.

**Comment by rdockterjr** [comment]
Thanks @borongyuan for the clarification
